version: "3"

services:
  mongo:
    image: mvertes/alpine-mongo:latest
  redis:
    image: redis:alpine
  integration-plugin-server:
    image: integration-plugin-server:latest
    build: ./integration-plugin-server
    volumes:
      - ./@volumes/package-files:/package-files
    environment:
      SERVER_INSTANCE_COUNT: 2
      SERVER_PORT: 8000
      SERVER_HOSTNAME: integration-plugin-server
    ports:
      - 8000:8000
  integration-worker:
    image: integration-worker:latest
    build: ./integration-worker
    volumes:
      - ./@volumes/packages:/packages
    environment:
      SERVER_INSTANCE_COUNT: 4
      SERVER_PORT: 9000
    ports:
      - 9000:9000
  integration-ui:
    image: integration-ui:latest
    build: ./integration-ui
    environment:
      PROXY_HTTP_PORT: 80
      PROXY_HOSTNAME: localhost
      PROXY_WORKER_URL: http://integration-worker:9000
      PROXY_PLUGIN_SERVER_URL: http://integration-plugin-server:8000
      PROXY_KEEPALIVE_TIMEOUT: 600s
    ports:
      - 80:80
